### ISSUE TITLE
Unable to install oracle java through apt

### ISSUE THREAD

**Issue by julien-h** [WhitewaterFoundry/WLinux#227]
WLinux is not compatible with oracle java?

When running:

```sudo add-apt-repository ppa:webupd8team/java```

I get

```Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for WLinux/buster```

**Comment by sirredbeard** [comment]
You may need to install lsb-release and edit /etc/lsb-release to match Debian buster.

**Comment by patrick330602** [comment]
Actually `add-apt-repository` is not supported on Debian systems. `add-apt-repository` is only supported on Ubuntu and its forks. Please do not use it.

**Comment by julien-h** [comment]
Here is the output of `lsb_release -a`:

```
No LSB modules are available.
Distributor ID: WLinux
Description:    WLinux GNU/Linux testing (buster)
Release:          testing
Codename:     buster
```

But the file `/etc/lsb-release` does not exist
